src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $user;

    /**
     * @ORM\ManyToOne(targetEntity=Event::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?Event $event;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     */
    private ?string $final_price;

    /**
     * @ORM\Column(type="datetime", options={"default": "CURRENT_TIMESTAMP"})
     */
    private ?DateTimeInterface $created_at;

    public function __construct()
    {
        $this->created_at = new DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getFinalPrice(): ?string
    {
        return $this->final_price;
    }

    public function setFinalPrice(string $final_price): self
    {
        $this->final_price = $final_price;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=EventRepository::class)
 */
class Event
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private ?string $name;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank
     */
    private ?string $description;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank
     */
    private ?DateTimeInterface $start_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private ?DateTimeInterface $end_date;

    /**
     * @ORM\Column(type="time")
     * @Assert\NotBlank
     */
    private ?DateTimeInterface $start_time;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private ?DateTimeInterface $end_time;

    /**
     * @ORM\Column(type="decimal", precision=6, scale=2)
     * @Assert\NotBlank
     */
    private ?string $price;

    /**
     * @ORM\Column(type="decimal", precision=4, scale=2, nullable=true)
     * @Assert\Range(
     *     min="0",
     *     max="99.99",
     *     notInRangeMessage="Please input a valid discount % in the xx.xx format."
     * )
     */
    private ?string $discount;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Image(maxSize="100k")
     */
    private ?string $image;

    /**
     * @ORM\ManyToMany(targetEntity=Musician::class, inversedBy="events")
     * @Assert\NotBlank
     */
    private Collection $musicians;

    /**
     * @ORM\ManyToMany(targetEntity=Venue::class, inversedBy="events")
     * @Assert\NotBlank
     */
    private Collection $venues;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="event", orphanRemoval=true)
     */
    private Collection $bookings;

    /**
     * @ORM\Column(type="integer", options={"default":"365"})
     * @Assert\Range(
     *     min="0",
     *     max="999",
     *     notInRangeMessage="Invalid number of days."
     * )
     * @Assert\Expression("value > this.getDiscountEnd()", message="Number of days must be greater than discount end days.")
     */
    private ?int $discount_begin;

    /**
     * @ORM\Column(type="integer", options={"default":"30"})
     * @Assert\Range(
     *     min="0",
     *     max="999",
     *     notInRangeMessage="Invalid number of days."
     * )
     */
    private ?int $discount_end;

    public function __construct()
    {
        $this->musicians = new ArrayCollection();
        $this->venues = new ArrayCollection();
        $this->bookings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getStartDate(): ?DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getStartTime(): ?DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(DateTimeInterface $start_time): self
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(?DateTimeInterface $end_time): self
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getPrice(): ?string
    {
        return $this->price;
    }

    public function setPrice(string $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDiscount(): ?string
    {
        return $this->discount;
    }

    public function setDiscount(?string $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Musician[]
     */
    public function getMusicians(): Collection
    {
        return $this->musicians;
    }

    public function addMusician(Musician $musician): self
    {
        if (!$this->musicians->contains($musician)) {
            $this->musicians[] = $musician;
        }

        return $this;
    }

    public function removeMusician(Musician $musician): self
    {
        if ($this->musicians->contains($musician)) {
            $this->musicians->removeElement($musician);
        }

        return $this;
    }

    /**
     * @return Collection|Venue[]
     */
    public function getVenues(): Collection
    {
        return $this->venues;
    }

    public function addVenue(Venue $venue): self
    {
        if (!$this->venues->contains($venue)) {
            $this->venues[] = $venue;
        }

        return $this;
    }

    public function removeVenue(Venue $venue): self
    {
        if ($this->venues->contains($venue)) {
            $this->venues->removeElement($venue);
        }

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setEvent($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getEvent() === $this) {
                $booking->setEvent(null);
            }
        }

        return $this;
    }

    public function getDiscountBegin(): ?int
    {
        return $this->discount_begin;
    }

    public function setDiscountBegin(int $discount_begin): self
    {
        $this->discount_begin = $discount_begin;

        return $this;
    }

    public function getDiscountEnd(): ?int
    {
        return $this->discount_end;
    }

    public function setDiscountEnd(int $discount_end): self
    {
        $this->discount_end = $discount_end;

        return $this;
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\Event;
use App\Repository\BookingRepository;
use App\Service\EventProcessor;
use Dompdf\Dompdf;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/booking")
 */
class BookingController extends AbstractController
{
    private const CANCEL_BOOKING_DAYS = 7;

    /**
     * @Route("/new/{id}", name="booking_new", methods={"POST"})
     * @param Event $event
     * @return Response
     * @throws Exception
     * @IsGranted("ROLE_USER")
     */
    public function new(Event $event): Response
    {
        $booking = new Booking();
        $user = $this->getUser();

        if ($user){
            $booking->setUser($this->getUser());
            $booking->setEvent($event);

            $eventProcessor = new EventProcessor($event);

            $booking->setFinalPrice($eventProcessor->getFinalPrice());

            $em = $this->getDoctrine()->getManager();
            $em->persist($booking);
            $em->flush();

            return $this->redirectToRoute("booking_show", [
                'id' => $booking->getEvent()->getId()
            ]);
        }
    }

    /**
     * @Route("/show/{id}", name="booking_show", methods={"GET"})
     * @param Event $event
     * @param BookingRepository $bookingRepository
     * @return Response
     * @IsGranted("ROLE_USER")
     */
    public function show(Event $event, BookingRepository $bookingRepository): Response
    {
        $user = $this->getUser();
        $hasBillingAddress = $user->hasBillingAddress();
        $userBooking = $bookingRepository->findByUser($user);
        $isBooked = $bookingRepository->isUserBooked($user);
        $isBookedToEvent = $bookingRepository->isUserBookedToEvent($user, $event);

        $eventProcessor = new EventProcessor($event);
        $currentDiscount = $eventProcessor->getCurrentDiscount();
        $finalPrice = $eventProcessor->getFinalPrice();
        $isCancellable = $eventProcessor->getDaysUntilEvent() <= self::CANCEL_BOOKING_DAYS ? false : true;

        return $this->render('booking/show.html.twig', [
            'user' => $user,
            'event' => $event,
            'currentDiscount' => $currentDiscount,
            'finalPrice' => $finalPrice,
            'userBooking' => $userBooking,
            'isBooked' => $isBooked,
            'isBookedToEvent' => $isBookedToEvent,
            'isCancellable' => $isCancellable,
            'hasBillingAddress' => $hasBillingAddress,
        ]);
    }

    /**
     * @Route("/{id}/pdf", name="booking_show_pdf", methods={"GET", "POST"})
     * @param Event $event
     * @param BookingRepository $bookingRepository
     * @return Response
     * @IsGranted("ROLE_USER")
     * @throws Exception
     */
    public function showPdf(Event $event, BookingRepository $bookingRepository): Response
    {
        $user = $this->getUser();
        $hasBillingAddress = $user->hasBillingAddress();
        $userBooking = $bookingRepository->findByUser($user);

        $eventProcessor = new EventProcessor($event);
        $currentDiscount = $eventProcessor->getCurrentDiscount();
        $finalPrice = $eventProcessor->getFinalPrice();

        $html = $this->renderView('booking/showPdf.html.twig', [
            'user' => $user,
            'event' => $event,
            'currentDiscount' => $currentDiscount,
            'finalPrice' => $finalPrice,
            'userBooking' => $userBooking,
            'hasBillingAddress' => $hasBillingAddress,
        ]);

        $dompdf = new Dompdf();
        $dompdf->loadHtml($html);
        $dompdf->setPaper('A4', 'landscape');

        $options = $dompdf->getOptions();
        $options->setIsHtml5ParserEnabled('true');

        $dompdf->setOptions($options);
        $dompdf->render();

        return new Response($dompdf->stream());
    }

    /**
     * @Route("/{id}", name="booking_delete", methods={"DELETE"})
     * @param Request $request
     * @param Booking $booking
     * @return Response
     * @IsGranted("ROLE_USER")
     */
    public function delete(Request $request, Booking $booking): Response
    {
        if ($this->isCsrfTokenValid('delete'.$booking->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($booking);
            $entityManager->flush();
        }

        return $this->redirectToRoute("booking_show", ['id' => $booking->getEvent()->getId()]);
    }
}

templates/booking/index.html.twig
<!DOCTYPE html>

<title>Hello BookingController!</title>

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/var/www/html/eventzone/src/Controller/BookingController.php'|file_link(0) }}">src/Controller/BookingController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/var/www/html/eventzone/templates/booking/index.html.twig'|file_link(0) }}">templates/booking/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/booking/show.html.twig
{% extends 'home/base.html.twig' %}

{% block title %}Booking | {{ event.name }}{% endblock %}

{% block body %}
<h3>Booking | <strong>{{ event.name }}</strong></h3>

<!-- Content wrapper start -->
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card border">
            <div class="row">
                <div class="col-sm-6">
                    <div class="card p-0 border">
                        <div class="content">
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-user"></i>
                                {{ user.firstName }} {{ user.lastName }}
                            </h2>
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-envelope"></i>
                                {{ user.email }}
                            </h2>
                        </div>
                    </div>
                    {% if hasBillingAddress is same as(true) %}
                    <div class="card p-0 border">
                        <div class="content">
                            <h4>Billing Address</h4>
                            <p class="text-muted">
                                {{ user.address }} {{ user.postcode }}
                                {{ user.city }}
                            </p>
                            <p class="text-muted">
                                {{ user.country }}
                            </p>
                        </div>
                    </div>
                    {% else %}
                    <div class="card p-0 border">
                        <div class="content">
                            <h3 class="text-danger">
                                <i class="fas fa-exclamation-triangle"></i> Please update your billing address in the settings menu.
                            </h3>
                        </div>
                    </div>
                    {% endif %}
                    <div class="card p-0 border">
                        <div class="content">
                            <h4>Price</h4>
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-money-bill"></i>
                                {{ event.price }}
                            </h2>
                            <hr>
                            {% if currentDiscount is not same as(0) and currentDiscount is not null %}
                            <h4 class="font-weight-bold">
                                <i class="fas fa-crow" style="color: orangered"></i> Early Bird Discount
                            </h4>
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-tags" style="color: orangered"></i>
                                {{ currentDiscount }} %
                            </h2>
                            <hr>
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-money-bill"></i>
                                Price: {{ finalPrice }}
                            </h2>
                            {% endif %}
                        </div>
                    </div>
                </div>

                <div  class="col-sm-6">
                    <div class="mw-full">
                        <div class="card p-0 border">

                            <img src="{{ asset('img/events/' ~ event.image)}}" class="img-fluid rounded-top" alt="Event image">

                            <div class="content">
                                <h2 class="content-title font-weight-bolder">
                                    {{ event.name }}
                                </h2>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <h4 class="font-weight-bold">Featuring: </h4>
                                        {% for musician in event.musicians %}
                                            <h3 class="content-title font-weight-bold">
                                                <i class="fas fa-music"></i> {{ musician.name }}
                                            </h3>
                                        {% endfor %}
                                        <h4 class="font-weight-bold">Location: </h4>
                                        {% for venue in event.venues %}
                                        <p class="text-muted">
                                            {{ venue.name }}
                                            <i class="fas fa-user"></i> {{ venue.capacity }}
                                        </p>
                                        <p class="text-muted">
                                            {{ venue.address }} {{ venue.postcode }}
                                            {{ venue.city }}
                                        </p>
                                        <p class="text-muted">
                                            {{ venue.country }}
                                        </p>
                                        <hr>
                                    </div>
                                    <div class="col-sm-6">
                                        <h5 class="font-weight-bolder">
                                            Date:
                                            <strong>{{ event.startDate|date('d | m | Y') }}</strong>
                                        </h5>
                                        <h5 class="font-weight-bolder">
                                            Time:
                                            <strong>{{ event.startTime|date('H:i', '+00:00 GMT') }}</strong> |
                                            <small>+00:00 GMT</small>
                                        </h5>
                                    </div>
                                </div>

                                {% endfor %}
                                {% if not isBooked and hasBillingAddress is same as(true) %}
                                    <div class="text-right">
                                        <form action="{{ path('booking_new', {'id': event.id}) }}" method="post">
                                            <button class="btn btn-lg btn-event font-weight-bold ">
                                                <i class="fas fa-check"></i> Confirm
                                            </button>
                                        </form>
                                    </div>
                                {% endif %}
                                {% if isBookedToEvent %}
                                    <div class="d-flex justify-content-end">
                                        <form action="{{ path('booking_show_pdf', {'id': event.id}) }}" method="post" class="pr-10">
                                            <button class="btn btn-lg font-weight-bold"><i class="fas fa-file-pdf"></i> Get PDF</button>
                                        </form>
                                        <form action="{{ path('booking_delete', {'id': userBooking.id}) }}"
                                              onsubmit="return confirm('Are you sure you want to cancel your event booking?');"
                                              method="post">
                                            <input type="hidden" name="_method" value="DELETE">
                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ userBooking.id) }}">
                                            <button class="btn btn-lg font-weight-bold btn-danger"><i class="fas fa-times"></i> Cancel</button>
                                        </form>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- Content wrapper end -->

{% endblock %}

templates/booking/showPdf.html.twig
{% block body %}
    <h3>Booking | <strong>{{ event.name }}</strong></h3>

<!-- Content wrapper start -->
<div class="content-wrapper">
    <div class="container-fluid">
        <div class="card border">
            <div class="row">
                <div class="col-sm-6">
                    <div class="card p-0 border">
                        <div class="content">
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-user"></i>
                                {{ user.firstName }} {{ user.lastName }}
                            </h2>
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-envelope"></i>
                                {{ user.email }}
                            </h2>
                        </div>
                    </div>
                    {% if hasBillingAddress is same as(true) %}
                        <div class="card p-0 border">
                            <div class="content">
                                <h4>Billing Address</h4>
                                <p class="text-muted">
                                    {{ user.address }}, {{ user.city }}
                                </p>
                                <p class="text-muted">
                                    {{ user.postcode }}, {{ user.country }}
                                </p>
                            </div>
                        </div>
                    {% else %}
                        <div class="card p-0 border">
                            <div class="content">
                                <h3 class="text-danger">
                                    <i class="fas fa-exclamation-triangle"></i> Please update your billing address in the settings menu.
                                </h3>
                            </div>
                        </div>
                    {% endif %}
                    <div class="card p-0 border">
                        <div class="content">
                            <h4>Price</h4>
                            <h2 class="content-title font-weight-bolder">
                                <i class="fas fa-money-bill"></i>
                                {{ event.price }}
                            </h2>
                            <hr>
                            {% if currentDiscount is not same as(0) and currentDiscount is not null %}
                                <h4 class="font-weight-bold">
                                    <i class="fas fa-crow" style="color: orangered"></i> Early Bird Discount
                                </h4>
                                <h2 class="content-title font-weight-bolder">
                                    <i class="fas fa-tags" style="color: orangered"></i>
                                    {{ currentDiscount }} %
                                </h2>
                            {% endif %}
                                <hr>
                                <h2 class="content-title font-weight-bolder">
                                    <i class="fas fa-money-bill"></i>
                                    Price: {{ finalPrice }}
                                </h2>
                         </div>
                    </div>
                </div>

                <div  class="col-sm-6">
                    <div class="mw-full">
                        <div class="card p-0 border">
                            <div class="content">
                                <h2 class="content-title font-weight-bolder">
                                    {{ event.name }}
                                </h2>
                                <hr>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <h4 class="font-weight-bold">Featuring: </h4>
                                        {% for musician in event.musicians %}
                                            <h3 class="content-title font-weight-bold">
                                                <i class="fas fa-music"></i> {{ musician.name }}
                                            </h3>
                                        {% endfor %}
                                        <h4 class="font-weight-bold">Location: </h4>
                                        {% for venue in event.venues %}
                                        <p class="text-muted">
                                            {{ venue.name }}
                                            <i class="fas fa-user"></i> {{ venue.capacity }}
                                        </p>
                                        <p class="text-muted">
                                            {{ venue.address }} {{ venue.postcode }}
                                            {{ venue.city }}
                                        </p>
                                        <p class="text-muted">
                                            {{ venue.country }}
                                        </p>
                                        <hr>
                                    </div>
                                    <div class="col-sm-6">
                                        <h6>
                                            Date:
                                            <strong>{{ event.startDate|date('d | m | Y') }}</strong>
                                        </h6>
                                        <h6>
                                            Time:
                                            <strong>{{ event.startTime|date('H:i', '+00:00 GMT') }} </strong>
                                        </h6>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- Content wrapper end -->

{% endblock %}